name: Unit Tests

on:
    push:
        branches:
            - master
            - bso
    pull_request:

jobs:
    test:
        name: Node v${{ matrix.node_version }} - ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node_version: [14.14.0]
                os: [ubuntu-latest, windows-latest]

        steps:
            - name: Checkout Project
              uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node_version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node_version }}
            - name: Restore CI Cache
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.os }}-${{ matrix.node_version }}-${{ hashFiles(matrix.os == 'windows-latest' && '**\yarn.lock' || '**/yarn.lock') }}
            - name: Install Dependencies
              run: yarn
            - name: Copy Configuration
              run: |
                  pushd src &&
                  cp config.example.ts config.ts &&
                  popd
            - name: Test
              run: yarn test
            - name: Upload coverage data to Codecov
              uses: codecov/codecov-action@v1